import { useMemo, useState } from 'react'
import './App.css'

const SEMESTER_START = '2026-08-29'
const SEMESTER_END = '2026-11-29'
const DANGER_THRESHOLD = 75
const TARGET = 90

const sections = {
  'IV-ECE-A': { label: 'IV ECE · Section A', slots: { Mon: 'C,,A,D,,,,,', Tue: 'C,D,B,F,,,,,', Wed: 'B,LAB,E,F,,,,,', Thu: 'F,A,E,B,,,,,', Fri: 'C,A,D,E,,,,,' }, subjects: { A: 'Behavioural Psychology', B: 'Wireless Comm & Antenna Systems', C: 'Computer Comm & Network Security', D: 'Semiconductor Memory Design', E: 'Scripting Language for EDA', F: 'Machine Learning for All', LAB: 'CCNS Lab' } },
  'IV-ECE-B': { label: 'IV ECE · Section B', slots: { Mon: 'C,A,E,F,,,,,', Tue: 'C,E,F,B,,,,,', Wed: 'C,D,A,B,,,,,', Thu: 'D,B,LAB,A,,,,,', Fri: 'E,D,F,,,,,,' }, subjects: { A: 'Behavioural Psychology', B: 'Wireless Comm & Antenna Systems', C: 'Computer Comm & Network Security', D: 'Semiconductor Memory Design', E: 'Scripting Language for EDA', F: 'Machine Learning for All', LAB: 'CCNS Lab' } },
  'III-ECE-A': { label: 'III ECE · Section A', slots: { Mon: 'E,B,B,A,,G,G,,', Tue: 'H,D,B,BP,,,G,,', Wed: 'C,A,D,F,,,,LAB,LAB', Thu: 'A,E,C,F,,,,,', Fri: 'D,A,E,C,,LAB,LAB,,' }, subjects: { A: 'Discrete Mathematics', B: 'Microprocessor, Microcontroller & Interfacing', BP: 'Microprocessor (B-Proj)', C: 'VLSI Design & Technology', D: 'System & Network on Chip', E: 'Machine Learning for All', F: 'Community Connect', G: 'Analytical & Logical Thinking Skills', H: 'Indian Art Form', LAB: 'VLSI/Microprocessor Lab' } },
  'III-ECE-B': { label: 'III ECE · Section B', slots: { Mon: 'LAB,LAB,,,,E,B,A,D', Tue: 'G,G,,,,F,B,D,C', Wed: 'G,,,,,BP,B,A,H', Thu: 'LAB,LAB,,,,A,C,E,F', Fri: ',,,,,C,A,E,D' }, subjects: { A: 'Discrete Mathematics', B: 'Microprocessor, Microcontroller & Interfacing', BP: 'Microprocessor (B-Proj)', C: 'VLSI Design & Technology', D: 'System & Network on Chip', E: 'Machine Learning for All', F: 'Community Connect', G: 'Analytical & Logical Thinking Skills', H: 'Indian Art Form', LAB: 'VLSI/Microprocessor Lab' } },
  'III-ECE-DS': { label: 'III ECE · Data Science', slots: { Mon: 'E,B,C,A,,,,,', Tue: 'C,B,D,F,,LAB,LAB,,', Wed: 'H,B,A,C,,,,G,G', Thu: 'A,D,E,F,,,,,', Fri: 'D,A,E,BP,,G,,LAB,LAB' }, subjects: { A: 'Discrete Mathematics', B: 'Microprocessor, Microcontroller & Interfacing', BP: 'Microprocessor (B-Proj)', C: 'VLSI Design & Technology', D: 'Machine Learning for All', E: 'Database Design & Management', F: 'Community Connect', G: 'Analytical & Logical Thinking Skills', H: 'Indian Art Form', LAB: 'VLSI/Microprocessor Lab' } },
  'II-BME': { label: 'II BME', slots: { Mon: 'E,C,I,I,,LAB,LAB,,', Tue: 'C,E,B,A,,H,H,,', Wed: 'B,D,A,,,H,G,,', Thu: 'A,E,B,D,,,,LAB,LAB', Fri: 'F,A,C,D,,,,G,G' }, subjects: { A: 'Transforms & Boundary Value Problems', B: 'Biomedical Signals & Systems', C: 'Electric & Electronic Circuits', D: 'Digital Logic for Medical Systems', E: 'Medical Physics', F: 'Professional Ethics', G: 'Universal Human Values-II', H: 'Verbal Reasoning', I: 'Social Engineering', LAB: 'DLMS/EEC Lab' } },
  'I-ECE-A': { label: 'I ECE · Section A', slots: { Mon: 'E,E,B,A,,CHEL,CHEL,F,CDC', Tue: 'C,B,A,D,,WS,WS,WS,WS', Wed: 'B,E,D,,,PPSL,PPSL,PCBL,PCBL', Thu: 'GER,GER,GER,A,,CDC,CDC,NSS,NSS', Fri: 'D,A,C,B,,F,GER,GER,GER' }, subjects: { E: 'Philosophy of Engineering', A: 'Advanced Calculus & Complex Analysis', B: 'Chemistry', C: 'Electronic System & PCB Design', D: 'Programming for Problem Solving', F: 'Biology', GER: 'German', WS: 'Basic Civil & Mechanical Workshop', CDC: 'General Aptitude', NSS: 'NSS', CHEL: 'Chemistry Lab', PPSL: 'PPS Lab', PCBL: 'PCB Lab' } },
  'I-ECE-B-EEE': { label: 'I ECE/EEE · Section B', slots: { Mon: 'CDC,F/G,CHEL,CHEL,,E,E,B,A', Tue: 'WS,WS,WS,WS,,C,B,A,D', Wed: 'F/G,PPSL,CDC,CDC,PPSL,,B,E,D', Thu: 'NSS,NSS,C,A,,D,GER,GER,GER', Fri: 'PCBL,PCBL,,GER,GER,GER,,B,A' }, subjects: { E: 'Philosophy of Engineering', A: 'Advanced Calculus & Complex Analysis', B: 'Chemistry', F: 'Electronic System & PCB Design', G: 'Electrical Circuits', D: 'Programming for Problem Solving', C: 'Biology', GER: 'German', WS: 'Basic Civil & Mechanical Workshop', CDC: 'General Aptitude', NSS: 'NSS', CHEL: 'Chemistry Lab', PPSL: 'PPS Lab', PCBL: 'PCB Lab' } },
  'I-ECE-DS': { label: 'I ECE · Data Science', slots: { Mon: 'F,CDC,PCBL,PCBL,,E,E,B,A', Tue: 'CHEL,CHEL,NSS,NSS,,C,B,A,D', Wed: 'CDC,CDC,A,,PPSL,PPSL,B,E,D', Thu: 'F,A,D,GER,GER,GER,,C,B', Fri: 'GER,GER,GER,,,WS,WS,WS,WS' }, subjects: { E: 'Philosophy of Engineering', A: 'Advanced Calculus & Complex Analysis', B: 'Chemistry', C: 'Electronic System & PCB Design', D: 'Programming for Problem Solving', F: 'Biology', GER: 'German', WS: 'Basic Civil & Mechanical Workshop', CDC: 'General Aptitude', NSS: 'NSS', CHEL: 'Chemistry Lab', PPSL: 'PPS Lab', PCBL: 'PCB Lab' } },
  'I-BIOTECH-B-BME': { label: 'I Biotech/BME · Section B', slots: { Mon: 'C,YOGA,YOGA,F/G,,E,E,A,B', Tue: 'CDC,CDC,C,F,,,B,A,D', Wed: 'WS,WS,WS,WS,,D,B,E,D', Thu: 'CHEL,CHEL,A,C/G,,B,JAP,JAP,JAP', Fri: 'F,CDC,A,JAP,JAP,JAP,,PPSL,PPSL' }, subjects: { E: 'Philosophy of Engineering', A: 'Advanced Calculus & Complex Analysis', B: 'Chemistry', D: 'Programming for Problem Solving', C: 'Cell Biology', F: 'Biochemistry', G: 'Human Physiology & Anatomy', JAP: 'Japanese', YOGA: 'Physical & Mental Health using Yoga', WS: 'Basic Civil & Mechanical Workshop', CDC: 'General Aptitude', CHEL: 'Chemistry Lab', PPSL: 'PPS Lab' } },
}

const dayIndexes = { Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5 }
const localDate = (value) => { const [year, month, day] = value.split('-').map(Number); return new Date(year, month - 1, day) }
const formatDate = (value) => localDate(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
const todayValue = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
function countClasses(section, subjectCode, fromDate, holidays, cancellations) { const start = localDate(fromDate); const end = localDate(SEMESTER_END); let total = 0; for (let cursor = new Date(start); cursor <= end; cursor.setDate(cursor.getDate() + 1)) { const weekday = Object.keys(dayIndexes).find((day) => dayIndexes[day] === cursor.getDay()); if (!weekday) continue; const key = dateKey(cursor); if (holidays.has(key)) continue; const slots = section.slots[weekday]?.split(',') || []; total += slots.filter((slot) => slot === subjectCode || slot.split('/').includes(subjectCode)).length; if (cancellations.has(`${key}:${subjectCode}`)) total -= 1 } return Math.max(0, total) }

function App() {
  const today = todayValue()
  const [sectionCode, setSectionCode] = useState('IV-ECE-A')
  const [planningDate, setPlanningDate] = useState(today < SEMESTER_START ? SEMESTER_START : today > SEMESTER_END ? SEMESTER_END : today)
  const [holidaysInput, setHolidaysInput] = useState('')
  const [cancellationsInput, setCancellationsInput] = useState('')
  const [showSettings, setShowSettings] = useState(false)
  const [records, setRecords] = useState(() => Object.fromEntries(Object.keys(sections['IV-ECE-A'].subjects).map((code) => [code, { conducted: '', attended: '' }])))
  const section = sections[sectionCode]
  const holidays = useMemo(() => new Set(holidaysInput.split(',').map((item) => item.trim()).filter(Boolean)), [holidaysInput])
  const cancellations = useMemo(() => new Set(cancellationsInput.split(',').map((item) => item.trim()).filter(Boolean)), [cancellationsInput])
  const rows = Object.entries(section.subjects).map(([code, name]) => { const record = records[code] || { conducted: '', attended: '' }; const conducted = Number(record.conducted) || 0; const attended = Math.min(Number(record.attended) || 0, conducted); const remaining = countClasses(section, code, planningDate, holidays, cancellations); const current = conducted ? (attended / conducted) * 100 : null; const dangerRequired = Math.max(0, Math.ceil(0.75 * (conducted + remaining) - attended)); const targetRequired = Math.max(0, Math.ceil(0.9 * (conducted + remaining) - attended)); const maximum = conducted ? ((attended + remaining) / (conducted + remaining)) * 100 : null; return { code, name, conducted, attended, remaining, current, dangerRequired, targetRequired, maximum } })
  const dangerCount = rows.filter((row) => row.maximum !== null && row.maximum < DANGER_THRESHOLD).length
  const targetCount = rows.filter((row) => row.maximum !== null && row.maximum < TARGET).length
  const enteredCount = rows.filter((row) => row.conducted > 0).length
  const updateRecord = (code, key, value) => setRecords((current) => ({ ...current, [code]: { ...(current[code] || {}), [key]: value } }))
  const changeSection = (value) => { setSectionCode(value); setRecords(Object.fromEntries(Object.keys(sections[value].subjects).map((code) => [code, { conducted: '', attended: '' }]))) }

  return (
    <main className="app-shell">
      <header className="topbar"><div className="brand-mark">AP</div><div><p className="eyebrow">Student planning tool</p><h1>Attendance Predictor</h1></div><div className="semester-chip"><span className="live-dot" /> 2026 semester</div></header>
      <section className="intro"><div><p className="eyebrow coral">Your semester, mapped</p><h2>Know exactly where<br /><em>you stand.</em></h2><p className="intro-copy">Make your attendance plan before the calendar gets crowded. Every number below follows your section's actual timetable.</p></div><div className="date-card"><span className="date-label">Today's date</span><strong>{formatDate(today)}</strong><span className="date-note">System date detected automatically</span></div></section>
      <section className="controls panel"><label><span>Class section</span><select value={sectionCode} onChange={(event) => changeSection(event.target.value)}>{Object.entries(sections).map(([code, item]) => <option key={code} value={code}>{item.label}</option>)}</select></label><label><span>Preferred planning date</span><input type="date" value={planningDate} min={SEMESTER_START} max={SEMESTER_END} onChange={(event) => setPlanningDate(event.target.value)} /><small>Counting classes from {formatDate(planningDate)}</small></label><button className="settings-button" type="button" onClick={() => setShowSettings(!showSettings)}>{showSettings ? 'Close schedule settings' : 'Adjust holidays & cancellations'} <span>↗</span></button></section>
      {showSettings && <section className="schedule-settings panel"><div><p className="eyebrow">Schedule exceptions</p><h3>Make the plan match reality</h3><p>Use ISO dates separated by commas. Cancellations use <code>YYYY-MM-DD:SUBJECT_CODE</code>.</p></div><label><span>Holidays</span><input value={holidaysInput} onChange={(event) => setHolidaysInput(event.target.value)} placeholder="2026-10-02, 2026-10-20" /></label><label><span>Cancelled classes</span><input value={cancellationsInput} onChange={(event) => setCancellationsInput(event.target.value)} placeholder="2026-10-05:A, 2026-10-12:LAB" /></label></section>}
      <section className="status-strip"><div><span className="status-icon">↗</span><div><strong>{enteredCount} of {rows.length}</strong><span>subjects entered</span></div></div><div><span className="status-icon mint">◷</span><div><strong>{Math.max(0, Math.ceil((localDate(SEMESTER_END) - localDate(planningDate)) / 86400000))}</strong><span>days in planning window</span></div></div><div><span className="status-icon amber">!</span><div><strong>{dangerCount || '—'}</strong><span>irreversible danger cases</span></div></div></section>
      <section className="section-heading"><div><p className="eyebrow">Subject breakdown</p><h2>Attendance outlook</h2></div><div className="legend"><span><i className="dot green" /> On track</span><span><i className="dot amber-dot" /> Watch closely</span><span><i className="dot red" /> Cannot recover</span></div></section>
      <section className="subject-list">{rows.map((row) => <article className="subject-row" key={row.code}><div className="subject-info"><div className="subject-code">{row.code}</div><div><h3>{row.name}</h3><p>{row.remaining} scheduled {row.remaining === 1 ? 'class' : 'classes'} remaining</p></div></div><div className="number-fields"><label>Conducted<input type="number" min="0" value={records[row.code]?.conducted || ''} onChange={(event) => updateRecord(row.code, 'conducted', event.target.value)} placeholder="0" /></label><label>Attended<input type="number" min="0" value={records[row.code]?.attended || ''} onChange={(event) => updateRecord(row.code, 'attended', event.target.value)} placeholder="0" /></label></div><div className={`current-percent ${row.current !== null && row.current < DANGER_THRESHOLD ? 'bad' : row.current !== null && row.current < TARGET ? 'watch' : ''}`}><span>Current</span><strong>{row.current === null ? '—' : `${row.current.toFixed(1)}%`}</strong></div><div className="outlook"><div><span>Need for 75%</span><strong className={row.dangerRequired > row.remaining ? 'danger-text' : ''}>{row.conducted ? (row.dangerRequired > row.remaining ? 'Impossible' : `${row.dangerRequired} classes`) : '—'}</strong></div><div><span>Need for 90%</span><strong className={row.targetRequired > row.remaining ? 'muted-text' : ''}>{row.conducted ? (row.targetRequired > row.remaining ? 'Unreachable' : `${row.targetRequired} classes`) : '—'}</strong></div></div><div className="max-finish"><span>Max finish</span><strong>{row.maximum === null ? '—' : `${row.maximum.toFixed(1)}%`}</strong></div></article>)}</section>
      <section className="summary-grid"><article className={`warning-card ${dangerCount ? 'warning' : 'clear'}`}><div className="warning-symbol">{dangerCount ? '!' : '✓'}</div><div><p className="eyebrow">{dangerCount ? 'Irreversible detention risk' : 'Danger threshold protected'}</p><h3>{dangerCount ? `${dangerCount} subject${dangerCount === 1 ? '' : 's'} cannot reach 75%` : 'Your entered subjects can still recover'}</h3><p>{dangerCount ? 'Even perfect attendance from your planning date would finish below the 75% threshold. Speak with your department early.' : 'Keep the required classes in view and update this plan when the timetable changes.'}</p></div></article><article className="target-card"><div className="target-ring"><span>{TARGET}%</span></div><div><p className="eyebrow">Target attendance</p><h3>{targetCount ? `${targetCount} target${targetCount === 1 ? '' : 's'} need a perfect run` : '90% is within reach'}</h3><p>{targetCount ? 'These subjects need more classes than are available, but the 75% danger calculation is shown separately.' : 'The target is ambitious by design. Use the required count to pace your week.'}</p></div></article></section>
      <footer><span>Semester window · {formatDate(SEMESTER_START)} — {formatDate(SEMESTER_END)}</span><span><i className="dot green" /> Timetable-aware calculations</span></footer>
    </main>
  )
}

export default App
